Listen = ":8080"
TemplateDir = "html"
RedisUrl = "redis://localhost:6379"
CacheTtl = 3600 # in seconds
ReverseLookup = true
PortLookup = true
ShowSponsor = true
Database = "ipstack" # use "IP Stack" or "GeoIP"
TrustedHeaders = []
Profile = false # enable profiling
Debug = false # enable debugging, ex print jwt token errors

[Jwt]
Enabled = false
SigningMethod = "HS256" # HS256 | HS384 | HS512
Secret = ""

[IPStack]
ApiKey = "HelloWorld"
UseHttps = true
EnableSecurity = true

[GeoIP]
CountryFile = ""
CityFile = ""
AsnFile = ""
