on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18.x"

      - name: Build EchoIP binary
        run: go build -o ./echoip ./cmd/echoip/main.go

      - name: Delete previous version
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
              sudo rm -rf ${{ secrets.PATH }}/echoip

      - name: Uploaded updated binary
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./echoip"
          overwrite: true
          target: ${{ secrets.PATH }}

      - name: Update permissions and restart service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
              sudo chown web:web ${{ secrets.PATH }}/echoip
              sudo systemctl restart ip 

