name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18.x"

      - name: Display Go version
        run: go version

      - name: Build EchoIP binary
        run: go build -o ./echoip ./cmd/echoip/main.go

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "echoip,etc/,html/"
