on:
  push:
    branches:
      - fix/added-currency-from-ipstack-response
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release-please:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18.x"

      - name: Build EchoIP binary
        run: go build -o ./echoip ./cmd/echoip/main.go

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          zip -r echoip-linux-amd64.zip echoip html LICENSE 

      - uses: google-github-actions/release-please-action@v3
        with:
          command: "manifest-pr"
          extra-files: |
            echoip-linux-amd64-${{  github.ref_name }}.zip 
            echoip 
            html 
            LICENSE
