name: Test

on:
  workflow_call:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18.x"

      - name: Run tests
        run: go test ./...
